import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/app/components/NavBar";
import { Providers } from "./GlobalRedux/provider";
("@/app/GlobalRedux/provider");
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main className="container mx-auto h-[calc(100vh-7rem)] flex justify-center items-center">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
